- hosts: webservers
  become: yes
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/home/misha/lab/test1/keys/misha_user.pub') }}"